### ISSUE TITLE
Suggestion - add the BibTex citation to your paper to the README.md

### ISSUE THREAD

**Issue by gjmulder** [HansikaPH/time-series-forecasting#4]
Hi Hansika,

You might want to add the BibTex citation for your paper to the README.md so that it is easy to both find and cite the paper:

```
@article{hewamalage2019recurrent,
  title={Recurrent Neural Networks for Time Series Forecasting: Current Status and Future Directions},
  author={Hewamalage, Hansika and Bergmeir, Christoph and Bandara, Kasun},
  journal={arXiv preprint arXiv:1909.00590},
  year={2019}
}
```

**Comment by gjmulder** [comment]
Also, minor feedback about your paper:

Firstly, Google Docs is really not a great place to store data that is referenced in a journal as the link could easily change. It would be better to publish your results in this Github repository as then the link  is unlikely to change.

Secondly, I think it is convention to highlight the best results per table in **bold** in a paper. It makes it easier to review and compare rows at a glance.

Finally, given your extensive pages of primary and secondary results are tabular and get a bit hard to read in your PDF you might want to additionally provide the results as .csv files, again in this Github repository.

**Comment by HansikaPH** [comment]
@gjmulder Thanks a lot for the feedback. I will take them into account in the next version of the manuscript.
