### ISSUE TITLE
Incorrect path for for files in  cif2016_augmented_experiments.sh 

### ISSUE THREAD

**Issue by ShankarChavan** [HansikaPH/time-series-forecasting#6]
Hi Hansika,

There is incorrect file location in the cif2016_augmented_experiments.sh 

![image](https://user-images.githubusercontent.com/6409350/66047101-ceb4c100-e544-11e9-992c-5f06499a9566.png)

instead it should be  **--binary_train_file datasets/binary_data/CIF_2016/augmented_data/stl_12i15.tfrecords**

**Comment by HansikaPH** [comment]
Hi Shankar,

Thanks for pointing this out. cif2016_augmented_experiments.sh file is an execution file used previously for certain testing. This is not used anymore. I will remove it from the repository.
